from blim_parser import FileAst, Function


class Codegen:
    def __init__(self, project_ast: dict[str, list[FileAst]]):
        self.project_ast = project_ast
        self.lines: list[str] = []

    def emit_instruction(self, instruction: str = ""):
        self.lines.append(f"\t{instruction}")

    def emit_label(self, label: str):
        self.lines.append(f"{label}:")

    def emit_raw(self, text: str = ""):
        self.lines.append(text)

    def gen_function(self, package: str, function: Function):
        self.emit_label(f"{package}__{function.name}")
        self.emit_instruction("ret")
        self.emit_raw()

    def generate_asm(self) -> str:
        self.emit_raw("; Generated by Blim for MANIAC 1.0")
        self.emit_raw()

        for package, files_ast in self.project_ast.items():
            for file_ast in files_ast:
                for function in file_ast.functions:
                    self.gen_function(package, function)

        return "\n".join(self.lines)
